<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto

namespace User;

if (false) {
    /**
     * This class is deprecated. Use User\User\Address instead.
     * @deprecated
     */
    class User_Address {}
}
class_exists(User\Address::class);
@trigger_error('User\User_Address is deprecated and will be removed in the next major release. Use User\User\Address instead', E_USER_DEPRECATED);

