# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: user.proto for package 'user'

require 'grpc'
require 'user_pb'

module User
  module UserService
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'user.UserService'

      rpc :Index, ::User::Empty, ::User::UserList
      rpc :Create, ::User::User, ::User::User
      rpc :Show, ::User::UserRequestId, ::User::UserResponse
    end

    Stub = Service.rpc_stub_class
  end
end
