# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("user.proto", :syntax => :proto3) do
    add_message "user.User" do
      optional :id, :int32, 1
      optional :name, :string, 2
      optional :email, :string, 3
    end
    add_message "user.Empty" do
    end
    add_message "user.UserList" do
      repeated :users, :message, 1, "user.User"
    end
    add_message "user.UserRequestId" do
      optional :id, :int32, 1
    end
    add_message "user.Error" do
      optional :code, :int32, 1
      optional :message, :string, 2
    end
    add_message "user.UserResponse" do
      optional :user, :message, 1, "user.User"
      optional :error, :message, 2, "user.Error"
    end
  end
end

module User
  User = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("user.User").msgclass
  Empty = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("user.Empty").msgclass
  UserList = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("user.UserList").msgclass
  UserRequestId = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("user.UserRequestId").msgclass
  Error = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("user.Error").msgclass
  UserResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("user.UserResponse").msgclass
end
